#Default policies

INPUT_POLICY=DENY
OUTPUT_POLICY=ALLOW
FORWARD_POLICY=DENY

#Description:
# All incoming LAN/WAN connections are blocked by default
# All outbound connections are allowed
# Access to services is handled via secure tunneling layer